### PR TITLE
Update to SQL Parser 4.1

### PR DESCRIPTION
**Pull request by nijel**
- it changes namespace to follow PSR-4
- it adds localization of the error messages

### CODE REVIEW

**Comment by cweiske** [comment]
This "simple" change leads to 30MiB dependencies. Previously `vendor/` was only 3.5MiB which then got stripped down.

```
$ du -hs vendor/
30M	vendor/

$ composer show --tree
pear/console_commandline v1.2.2 A full featured command line options and arguments parser.
├──ext-dom *
├──ext-xml *
├──pear/pear_exception ^1.0.0
│  └──php >=4.4.0
└──php >=5.3.0
phpmyadmin/sql-parser v4.1.0 A validating SQL lexer and parser with a focus on MySQL dialect.
├──ext-mbstring *
├──php >=5.3.0
└──phpmyadmin/motranslator ~3.0
   ├──php >=5.3.0
   └──symfony/expression-language ^3.1 || ^2.8
      ├──php >=5.5.9
      └──symfony/cache ~3.1
         ├──php >=5.5.9
         ├──psr/cache ~1.0
         │  └──php >=5.3.0
         └──psr/log ~1.0
            └──php >=5.3.0
```

Is there a way to not have all these dependencies?
I do not want translations.

**Comment by nijel** [comment]
The motranslator dependency might be optional in future, see https://github.com/phpmyadmin/sql-parser/issues/129

Update: This will actually happen on next release (4.2).

**Comment by nijel** [comment]
There is now 4.1.1 where the motranslator dependency is optional.

**Comment by cweiske** [comment]
I've merged the changes and released version 0.2.0. Thanks!

**Pull request closed without merging**
